# Generated by Django 5.1.3 on 2025-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='preview',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
