# Generated by Django 5.1.3 on 2025-05-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_preview_content_preview_image'),
        ('news', '0002_articletranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.preview'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
