# Generated by Django 5.1.3 on 2025-05-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_articletranslation_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='translated_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='translated_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='translated_title',
            field=models.CharField(max_length=200),
        ),
    ]
